version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper # https://hub.docker.com/r/wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka # https://hub.docker.com/r/wurstmeister/kafka/
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 #Zookeeper 정보
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1 #호스트
      KAFKA_ADVERTISED_HOST_PORT: 9092  # 포트번호
      KAFKA_CREATE_TOPICS: "test:1:1"   #Topic명:Partition개수:Replica개수
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
