spring:
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      group-id: 'myGroup'
      # auto-offset-reset : Kafka에 초기 오프셋이 없거나 현재 오프셋이 서버에 더 이상 존재하지 않는 경우 수행 할 작업
      # earliest : 오프셋을 가장 빠른 오프셋으로 자동 재설정
      # https://docs.confluent.io/platform/current/installation/configuration/consumer-configs.html
      auto-offset-reset: earliest



#spring:
#  kafka:
#    bootstrap-servers: 'localhost:9092'
